snapshot:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/22/44.yaml

packages:
- .

extra-deps:
  - ../../LocalPkgs/configfile

# extra-package-dbs: []

system-ghc: true

# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]
